### ISSUE TITLE
Docs Improvements Round 1 (started 2024-08-01)

### ISSUE THREAD

**Issue by vcavallo** [operating-function/pallas#2]
## General/Code

- [x] #1 
- [x] Update github tags with less esoteric terms (remove ssi, orthogonal persistence. Add operating system)

## Readme Content

Order:
  - [x] Intro (#4)
    - [x] #4
      - [x] Persistence for free; get a database just by writing functions
      - [x] Store partially applied functions; ship them over the wire
      - [x] System calls as part of persisted state (make hardware restarts invisible)
    - [x] Type definitions
    - [x] Broad strokes of overall system (current section might be too heavy on Sire)
      - [x] Remove claims that “Sire is not the point”—right now it is the point
      - [x] #6
  - [x] Video (some multi-cog or multi-ship demo. If we can pass a function between things that would be great)
  - [x] then run a cog
  - [x] #5
  - [x] then repl (briefly, then link to docs section on this)
  - [x] #7

## Documentation site

- [ ] Add “event source” style diagrams to explain system architecture (use two machine communication example?)
  - [ ] hand-drawn single-machine system architecture (runtime, VM, event log, host file system, etc.)
    - [ ] if something good results, polish it visually
- [ ] Update LC/supercombinator/how we’ll persist partially applied functions. Land the “Hook”
  - [ ] Better explanation of how we go from event-sourcing -> “DB engine just by writing functions”
- [ ] Explain cog cache / booting (“why can’t I just change the Sire file? Why do i have to delete the ship?”)
- [ ] Include explanation of merkle DAG, content addressing. (conceptual crutch: “functions are lookup tables”)
  - [ ] Include an example of O(1) lookup? Or just make the claim.
- [ ] Introduce “orthogonal persistence” and “exokernel” later than we do now. Define them once introduced (either here or linked elsewhere?)
- [ ] IO interface, hardware, and syscalls need much more explanation
- [x] Rework the section which claims you “get a database engine by just writing functions”
- [ ] Elaborate on how system calls can be part of state

## General Editing

- [ ] Pass to catch the use of undefined terms
- [ ] Pass of the generated documentation site to make sure markdown changes from recent issues render as expected
- [x] Where sensible, simple code examples should make use of a uniform layout style (don't use prefix if infix was previously introduced, etc)

**Comment by cvanetten** [comment]
Opening a new ticket with latest round of feedback from interviews. Closing this as `will not fix`
